name: RWA CI Pipeline

on:
  push:
    branches: [main, ci-cd-pipeline]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Set dummy environment variables
        run: |
          echo "VITE_AUTH0=false" >> .env
          echo "VITE_GOOGLE=false" >> .env
          echo "VITE_AWS_COGNITO=false" >> .env
          echo "VITE_OKTA=false" >> .env
  
      - name: Copy mock AWS Cognito files
        run: npm run predev:cognito:ci
      - name: Build Frontend
        run: npm run build:ci

  api-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Cypress UI Test
        uses: cypress-io/github-action@v6
        with:
          build: npm run build:ci
          start: npm start
          wait-on: 'http://localhost:3000'
          spec: cypress/tests/api/*.spec.ts

  ui-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Cypress UI Test
        uses: cypress-io/github-action@v6
        with:
          build: npm run build:ci
          start: npm start
          wait-on: 'http://localhost:3000'
          spec: cypress/tests/ui/*.spec.ts

  deploy:   
    needs: [api-test, ui-test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Placeholder
        run: echo "Deploy ke Render / Railway / Netlify"
